# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ more-than-two-days ]
  pull_request:
    branches: [ more-than-two-days ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: build client ci
      working-directory: client
      run: npm ci

    - name: build service ci
      working-directory: service
      run: npm ci

    - name: build client test
      working-directory: client
      run: npm test -- --coverage

    - name: build service test
      working-directory: service
      run: npm run test -- --coverage

    - name: build client test coverage
      uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        lcov-file: ./client/coverage/lcov.info      

    - name: build service test coverage
      uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        lcov-file: ./service/coverage/lcov.info      

    - name: build client build
      working-directory: client
      run: npm run build --if-present
